// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	gql "github.com/paypi/paypi-go/gql"
	mock "github.com/stretchr/testify/mock"
)

// GqlClient is an autogenerated mock type for the GqlClient type
type GqlClient struct {
	mock.Mock
}

// MakeRequest provides a mock function with given fields: query, respData
func (_m *GqlClient) MakeRequest(query gql.GqlQuery, respData interface{}) error {
	ret := _m.Called(query, respData)

	var r0 error
	if rf, ok := ret.Get(0).(func(gql.GqlQuery, interface{}) error); ok {
		r0 = rf(query, respData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
